### ISSUE TITLE
ModuleNotFoundError: No module named 'sdv.tabular'

### ISSUE THREAD

**Issue by lingleong981130** [gretelai/gretel-synthetics#173]
Traceback (most recent call last):
  File "c:\Users\1000312852\Desktop\gretel-synthetics\examples\test.py", line 2, in <module>
    from gretel_synthetics.actgan import ACTGAN
  File "C:\Users\1000312852\AppData\Local\Programs\Python\Python310\lib\site-packages\gretel_synthetics\actgan\__init__.py", line 1, in <module>
    from gretel_synthetics.actgan.actgan_wrapper import ACTGAN  # noqa
  File "C:\Users\1000312852\AppData\Local\Programs\Python\Python310\lib\site-packages\gretel_synthetics\actgan\actgan_wrapper.py", line 14, in <module>
    from sdv.tabular.base import BaseTabularModel
ModuleNotFoundError: No module named 'sdv.tabular'

**Comment by nina-xu** [comment]
Hi @lingleong981130 , ACTGAN requires `sdv<0.18.0`. What is the version of your sdv installation?

**Comment by mckornfield** [comment]
Going to close this as stale
